version: "3.3"

services:
  db:
    image: "postgres:14.1-alpine"
    container_name: postgres14
    user: postgres
    hostname: postreserv
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "moneytransf "  ]
      interval: 30s
      timeout: 60s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=moneytransf
    ports:
      - "5432:5432"

  moneytransferapp:
    container_name: moneytransferapp
    build: ./moneytransfapp
    environment:
      - DB_SERV=postreserv
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


networks:
  default:
